### ISSUE TITLE
文字多了之后，文章末尾后就会留大片空白

### ISSUE THREAD

**Issue by panggirl** [androiddevelop/AlignTextView#1]
![20150529151222](https://cloud.githubusercontent.com/assets/10395037/7878053/34864882-0615-11e5-9928-1939a5a3d48b.png)

**Comment by androiddevelop** [comment]
已修正，请使用新版本的AlignTextView

**Comment by panggirl** [comment]
空白还是有点   又出出现个问题 在三星手机上出现最后一行文字显示不全

**Comment by androiddevelop** [comment]
我近段时间看一下，尽快解决问题
