### ISSUE TITLE
用到html的时候图片显示不正常

### ISSUE THREAD

**Issue by luyangliu616** [androiddevelop/AlignTextView#13]
rs

**Comment by luyangliu616** [comment]
setText   Html.fromHtml  然后图片不正常

**Comment by androiddevelop** [comment]
如果使用html这种形式的，请使用原生TextView

**Comment by luyangliu616** [comment]
我读了下内容 个人觉得作者可以从 SpannableStringBuilder 入手 从spanstart和spanend入手 由于我自己主要目的还有显示video所以 我从SpannableStringBuilder 入手 把textview分解成webview imageview等多个 所以代码有点不一样 很感谢作者的代码

**Comment by androiddevelop** [comment]
恩，后续我研究一下，非常感谢
