### ISSUE TITLE
Can not support ImageSpan (不支持ImageSpan)

### ISSUE THREAD

**Issue by fancychendong** [androiddevelop/AlignTextView#15]
发现个问题，使用TextView显示多个ImageSpan内容时，TextView本身没有左右对齐的话，在TextView最后追加ImageSpan的时候会有问题。
本来想使用你这个库，但发现并不支持ImageSpan。。。
是否后续有支持的打算

**Comment by androiddevelop** [comment]
ImageSpan方面暂时不会支持。
