### ISSUE TITLE
ListView中item使用AlignTextView,5.0版本系统机器出现内容乱序现象

### ISSUE THREAD

**Issue by haichaoyuan** [androiddevelop/AlignTextView#16]
你好，大神，开发中测试包了个TextView文本框显示文字右边没对齐的bug,感谢您的开源组件，使我快速解决这个问题。

但是在测试过程中，发现Android系统版本4.1.2的三星机器，没出现问题，而Android系统版本5.0.2的三星机器出现乱序现象，具体表现为前面三项原先是A、B、C,列表下滑再回到顶部，前面三项变为B、A、C。初步怀疑是不是新版本系统优化TextView导致的。

在下qq 1830560854,欢迎一起解决问题,：）。

**Comment by androiddevelop** [comment]
可以试一下CBAlignTextView，最近有些忙，等闲了解决下这个问题

**Comment by haichaoyuan** [comment]
没事，我已经换回TextView了，还是感谢你，:)
