### ISSUE TITLE
设置maxLines和ellipsize有问题

### ISSUE THREAD

**Issue by xiaoxige** [androiddevelop/AlignTextView#24]
设置maxLines去限制最大的行数有问题，ellipsize超过后不显示省略号有问题

**Comment by androiddevelop** [comment]
如果使用maxLines和ellipsize属性的话，请使用CBAlignTextView。

**Comment by shuaimango** [comment]
使用CBAlignTextView出现了省略号，但align="right"不生效，没有右对齐。建议demo里给个示例
