### ISSUE TITLE
TextView展示带图片的Html

### ISSUE THREAD

**Issue by liukkevin** [androiddevelop/AlignTextView#3]
Html.fromHtml()里面的ImageGetter取回图片在AlignTextView上无法显示，在TextView上是没问题的。我看了您重写的onLayout和onDraw，又看了TextView源码里的onLayout onDraw，还是不得要领。不知道您能否帮助我解答，不胜感谢。

**Comment by androiddevelop** [comment]
如果你要加载网页，不推荐使用AlignTextView。
AlignTextView与CBAlignTextView是对文字进行对齐，如果文本仅仅显示，可以使用AlignTextView，不过还是推荐使用CBAlignTextView，CBAlignTextView保留了原生TextView基本所有的功能，可以看一下wiki。[https://github.com/androiddevelop/AlignTextView/wiki](https://github.com/androiddevelop/AlignTextView/wiki)
