### ISSUE TITLE
!!! CBAlignTextView 在XML文件中setText有个 NullPointerException BUG

### ISSUE THREAD

**Issue by dreamfish797** [androiddevelop/AlignTextView#37]
CBAlignTextView 在XML文件中setText 

    <com.shanbay.interview.functionCustomView.wediget.CBAlignTextView
        ...
        android:text="@string/shanbay_word"
        ...   />

在文本转化方法 process() 中会报错， List 对象 addCharPosition 为 null。

**Comment by androiddevelop** [comment]
2.3.1版本已经修复
