### ISSUE TITLE
请教一行代码的意思

### ISSUE THREAD

**Issue by hippyk** [androiddevelop/AlignTextView#38]
int ignoreCalcLength = (int) (width / oneChineseWidth); // 忽略计算的长度

1. 忽略计算 是什么意思？
2. 为什么只考虑中文字符的宽度

**Comment by androiddevelop** [comment]
因为一行全部显示中文时最长，所以忽略掉全部是中文时的字符树，一定能显示完的。

**Comment by hippyk** [comment]
@androiddevelop 谢谢！
