### ISSUE TITLE
lineSpacingExtra 问题

### ISSUE THREAD

**Issue by asker517** [androiddevelop/AlignTextView#4]
很棒的一种排版方法 只是我在使用过程中发现 lineSpacingExtra 设置越大 文字最后一行有可能会导致显示不全...

**Comment by androiddevelop** [comment]
您使用的是AlignTextView还是CBTextView

**Comment by asker517** [comment]
我用的是AlignTextView 感觉AlignTextView效果要比CBAlignTextView 要好 但是就是有这个问题的存在 CB貌似没有这个问题

**Comment by androiddevelop** [comment]
好的，我这两天看一下这个问题

**Comment by androiddevelop** [comment]
我这边看了一下，没问题的，应为getLineHeight已经包含了lineSpacingExtra，你的有截图么？是不是文字超出了之后没有设置滚动？
    
                android:lineSpacingExtra="7dp"
                android:ellipsize="marquee"

代码中需要对alignTextView进行设置
 
     alignTv.setMovementMethod(new ScrollingMovementMethod());

**Comment by asker517** [comment]
@androiddevelop 十分感谢。
