### ISSUE TITLE
width设置wrap_content就无效.

### ISSUE THREAD

**Issue by DarkSherlock** [androiddevelop/AlignTextView#42]
CBAlignTextView如果设置    android:layout_width="wrap_content" 而不是match_parent的话，CBAlignTextView的宽度会是0。希望可以重写onmeasure解决这个问题.

**Comment by androiddevelop** [comment]
CBAlignTextView的原理是更改了设置的text的内容，在内容里面添加了空格，默认的【android:layout_width】还是走的系统的测量方式，请确认下使用时该组件宽度确实不是0，可以粘贴一下布局代码。
