### ISSUE TITLE
CBAlignTextView在Listview或者Recyclerview中有时候settext无效bug

### ISSUE THREAD

**Issue by DarkSherlock** [androiddevelop/AlignTextView#43]
CBAlignTextView在我的项目里Listview中，如果手指一直拖动listview滑动，屏幕显示外的第一条数据就不会显示，如果是随意滑动的话就会显示.(比如listview一个屏幕只能显示5条数据，那么我拖动listview往上滑，那么第6条数据滑进屏幕的时候CBAlignTextView是不显示text的，但是如果我是快速滑动一下就松开，那么第6条数据是可以显示的。）后面我特地从githup下了你的example运行下，发现你的example里也有无效的情况。

![screenshot_2018-01-04-14-13-08-250_me codeboy android aligntextview example](https://user-images.githubusercontent.com/20508433/34552146-c8d1cf38-f15a-11e7-8370-b845b716ad23.png)

**Comment by DarkSherlock** [comment]
AlignTextView则不会存在这个问题

**Comment by androiddevelop** [comment]
系统版本是？

**Comment by DarkSherlock** [comment]
我的工程是22，用的是红米手机4.4运行的。你工程里的demo同样有这个问题，而且我发现，如果1个item显示无效，但是只要界面onresume比如我按home建后再打开这个页面，这个原本不显示的item就又显示了，大神

**Comment by androiddevelop** [comment]
复用CBAlignTextView的时候，setText前，调用reset()即可。
