### ISSUE TITLE
AlignTextView复制

### ISSUE THREAD

**Issue by yezhiren1991** [androiddevelop/AlignTextView#44]
AlignTextView 排版较好，怎么解决不能复制问题呢，CBAlignTextView排版不是太好，AlignTextView不能复制的原因是什么？

**Comment by androiddevelop** [comment]
因为AlignTextView是直接重写draw方法， 绘制文本的，没有使用对应复制行为，而CBAlignTextView是在TextView的基础上实现的，所以也具有TextView的选择复制功能。
