### ISSUE TITLE
当文本内容过多时候，滑动特别卡顿

### ISSUE THREAD

**Issue by ifbugfrog** [androiddevelop/AlignTextView#5]
卡顿到不能接受

**Comment by androiddevelop** [comment]
您使用的是哪一个？AlignTetView还是CBAlignTextView？

**Comment by ifbugfrog** [comment]
我没记错的话是AlignTextView

**Comment by androiddevelop** [comment]
已经更新，2.0.3,AlignTextView做了一些优化，计算时间至少减少一半，我在手机上试了下，没有卡顿现象，您试下看下。

**Comment by corcpp** [comment]
内容多的时候 滑动还是卡顿很严重

**Comment by androiddevelop** [comment]
如果对对齐要求不是特别高的话，可以使用CBAlignTextView，效率比AlignTextView高
