### ISSUE TITLE
会超出屏幕显示的范围

### ISSUE THREAD

**Issue by ludwigY** [androiddevelop/AlignTextView#7]
有时候字符串会超出屏幕显示的范围，比如红色字体部分，最后一个字符就超出了范围。
试着修改了一下，不过是在上一个版本上进行的修改，不知道正确与否。具体修改点如下：
①Line180   int ignoreCalcLength = (int) (width / oneChineseWidth + 0.99); 
→  int ignoreCalcLength = (int) (width / oneChineseWidth ); 
②Line200    i = i + ignoreCalcLength;
→ i = i + ignoreCalcLength-1;

![image](https://cloud.githubusercontent.com/assets/16536440/12086800/4cd7a494-b308-11e5-8498-762deea4aa9d.png)

**Comment by androiddevelop** [comment]
这个问题已经修复了，请使用2.3版本，您使用的应该是2.2
