### ISSUE TITLE
底部空白问题 & 显示不全

### ISSUE THREAD

**Issue by asker517** [androiddevelop/AlignTextView#8]
我在5.1.1的机器上还有6.0.1机型上跑 表现近乎完美，但是我用Gennymotion模拟器跑 低分辨率的设备上发现（480 * 800 还有960 * 540 ）底部空白问题还是偶尔存在，系统版本号是4.1.1 . 我是用在recyclerview中的。而这个多余的空白表现的很明显，会错乱。同时也有时候会出现文字没有显示全就被截断了. 感觉是Line size 计算有问题

**Comment by androiddevelop** [comment]
好的，我尽快查找原因

**Comment by zero47** [comment]
看了一下onLayout部分代码，底部留白是因为当原本10行的重新排版后变为9行，那一行的高度作者用了paddingBottom来处理，但是当paddingBottom是负数时并不生效，所以会多出空白行。
`int height = (int) ((textLineSpaceExtra + textHeight) * lines.size());
//            int heightGap = (int) ((textLineSpaceExtra + textHeight) * (lines.size() -
//                    originalLineCount));

//            setPaddingFromMe = true;
//            //调整textview的paddingBottom来缩小底部空白
//            setPadding(getPaddingLeft(), getPaddingTop(), getPaddingRight(),
//                    originalPaddingBottom + heightGap);

            getLayoutParams().height = height;`

**Comment by androiddevelop** [comment]
好的，我这几天具体看下，
